### Create a new conversation
POST http://localhost:8000/conversations
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxNzQzNTI0LCJleHAiOjE3NjE3NDcxMjR9.3r7IKcbYh1-haaf7mmwF8sPXU4MPWvLQyrs_F8e8lMY; Max-Age=3600; Expires=Wed, 29 Oct 2025 14:12:04 GMT; Path=/; HttpOnly

{
  "title": "Chat with Neko"
}

### Get all conversations for the user
GET http://localhost:8000/conversations
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxNzQzNTI0LCJleHAiOjE3NjE3NDcxMjR9.3r7IKcbYh1-haaf7mmwF8sPXU4MPWvLQyrs_F8e8lMY; Max-Age=3600; Expires=Wed, 29 Oct 2025 14:12:04 GMT; Path=/; HttpOnly